### ISSUE TITLE
Installation error!!! 

### ISSUE THREAD

**Issue by sidh104** [ChiChou/Grapefruit#6]
This error throw ups when i tried to install Grapefruit....

Is it an NPM issue?????

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-sass@4.14.1 install: `node scripts/install.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sidharth.b\AppData\Roaming\npm-cache\_logs\2020-07-13T19_02_51_293Z-debug.log
child_process.js:642
    throw err;
    ^

Error: Command failed: npm i
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:639:15)
    at Object.<anonymous> (D:\iOSKit\Grapefruit-master\scripts\install.js:7:6)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  status: 134,
  signal: null,
  output: [ null, null, null ],
  pid: 12264,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grapefruit@0.7.0 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grapefruit@0.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by sidh104** [comment]
yes its the problem with NPM version.... Sorted thanks 👍
